projects/modest_greeter/web/router.ex
defmodule ModestGreeter.Router do
  use ModestGreeter.Web, :router

  pipeline :browser do
  plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  scope "/", ModestGreeter do
  pipe_through :browser

  get "/",TopController,:index
  get "/about",TopController,:about
  get "/hello",HelloController,:show
  get "/hello/:name",HelloController,:show
  end
end

projects/modest_greeter/lib/modest_greeter/endpoint.ex
defmodule ModestGreeter.Endpoint do
  use Phoenix.Endpoint, otp_app: :modest_greeter

  socket "/socket", ModestGreeter.UserSocket

  # Serve at "/" the static files from "priv/static" directory.
  #
  # You should set gzip to true if you are running phoenix.digest
  # when deploying your static files in production.
  plug Plug.Static,
    at: "/", from: :modest_greeter, gzip: false,
    only: ~w(css fonts images js favicon.ico robots.txt)

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Logger

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Poison

  plug Plug.MethodOverride
  plug Plug.Head

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  plug Plug.Session,
    store: :cookie,
    key: "_modest_greeter_key",
    signing_salt: "l42lFwMt"

  plug ModestGreeter.Router
end

projects/modest_greeter/web/controllers/hello_controller.ex
defmodule ModestGreeter.HelloController do
    use ModestGreeter.Web,:controller

    def show(conn,params) do
        render conn, "show.html", name: params["name"] || "world"
    end
end

projects/modest_greeter/web/controllers/top_controller.ex
defmodule ModestGreeter.TopController do
  use ModestGreeter.Web,:controller
  def index(conn,_params) do
    render conn,"index.html"
  end

  def about(conn,_params) do
    render conn,"about.html"
  end
end

projects/modest_greeter/web/views/error_view.ex
defmodule ModestGreeter.ErrorView do
  use ModestGreeter.Web, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Internal server error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

projects/modest_greeter/web/views/hello_view.ex
defmodule ModestGreeter.HelloView do
    use ModestGreeter.Web,:view

    def document_title(assigns) do
      "ModestGreeter(#{assigns.name})"
    end
end

projects/modest_greeter/web/views/layout_view.ex
defmodule ModestGreeter.LayoutView do
  use ModestGreeter.Web, :view
end

projects/modest_greeter/web/views/top_view.ex
defmodule ModestGreeter.TopView do
  use ModestGreeter.Web,:view

  def document_title(assigns) do
    case assigns.view_template do
      "about.html" -> "ModestGreeter - このサイトについて"
      _ -> "ModestGreeter"
    end
  end
end

projects/modest_greeter/web/templates/hello/show.html.eex
<div class="card m-3">
  <%= tag :img,src: static_path(@conn,"/images/modest_greeter.svg"),
  alt: "Robot" ,style: "width: 100%;max-width: 320px",
  class: "card-image-top mx-auto" %>
</div>
  <div class="card-body text-white bg-success">
    <p class="card-text lead">
      <i class="fa fa-smile-o"></i>
      Hello,<%=@name %>!
    </p>
  </dev>
</dev>

projects/modest_greeter/web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title><%=@view_module.document_title assigns %></title>
    <%= tag :link,rel: "stylesheet",
    href: static_path(@conn,"/css/app.css") %>
    <%= tag :link,rel: "shortcut icon",type: "image/x-icon",
    href: static_path(@conn,"/images/modest_greeter.ico") %>
    <%= tag :link,rel: "apple-touch-icon",type: "image/xicon",
    href: static_path(@conn,"/images/modest_greeter256.png") %>
  </head>

  <body>
    <header>
      <h1><%= link "ModestGreeter",to: top_path(@conn, :index,[]) %></h1>
    </header>
    <main>
      <%= render @view_module, @view_template, assigns %>
    </main>
    <footer>
      &copy;2016 Oiax Inc.
    </footer>
    <%= content_tag :script, "",src: static_path(@conn,"/js/app.js") %>
  </body>
</html>

projects/modest_greeter/web/templates/top/about.html.eex
<dev class="m-3">
  <h1>このサイトについて</h1>
  <p>ModestGreeter は『Elixir/Phoenix 初級①』の学習用 Phoenix アプリです。</p>
</div>

projects/modest_greeter/web/templates/top/index.html.eex
<%
names = ~w(Alice Bob Charlie Takumi Seita Tomoharu Koki)
%>
<div class="jumbotron m-3">
  <h1 class="display-3"><%=document_title(assigns)%></h1>
  <p class="lead">ModestGreeter へようこそ!</p>
  <hr>
  <p><%= link "このサイトについて",to: top_path(@conn, :about, []) %></p>
</div>
<nav class="nav justify-content-center mb-3">
  <%= for name <- names do %>
  <%= link name, to: hello_path(@conn, :show ,name,[]), class: "nav-link" %>
  <%= end %>
</nav>